//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeFrontEnd {
	
	
	public partial class Blog {
		
		protected System.Web.UI.WebControls.Content place1;
		
		protected System.Web.UI.WebControls.Repeater rpt;
		
		protected System.Web.UI.WebControls.Label lblpostid;
		
		protected System.Web.UI.WebControls.Repeater inRpdt;
		
		protected System.Web.UI.WebControls.ImageButton likebu;
		
		protected System.Web.UI.WebControls.Label countlbllike;
		
		protected System.Web.UI.WebControls.ImageButton dislikebu;
		
		protected System.Web.UI.WebControls.Label countlbldislike;
		
		protected System.Web.UI.WebControls.ImageButton heartbu;
		
		protected System.Web.UI.WebControls.Label countlblheart;
		
		protected System.Web.UI.WebControls.ImageButton brokenheart;
		
		protected System.Web.UI.WebControls.Label countlblbrokenheart;
		
		protected System.Web.UI.WebControls.ImageButton hahabu;
		
		protected System.Web.UI.WebControls.Label countlblhaha;
		
		protected System.Web.UI.WebControls.ImageButton Angrybu;
		
		protected System.Web.UI.WebControls.Label countlblangry;
		
		protected System.Web.UI.WebControls.LinkButton react;
		
		protected System.Web.UI.WebControls.TextBox ctext;
		
		protected System.Web.UI.WebControls.LinkButton bureadmore;
		
		protected System.Web.UI.WebControls.Label badlbl;
		
		protected System.Web.UI.WebControls.Label regslbl;
		
		protected System.Web.UI.WebControls.Content place2;
		
		protected System.Web.UI.WebControls.Content place3;
	}
}
