//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeFrontEnd {
	
	
	public partial class login {
		
		protected System.Web.UI.WebControls.Content place1;
		
		protected System.Web.UI.WebControls.TextBox FirstName;
		
		protected System.Web.UI.WebControls.TextBox LastName;
		
		protected System.Web.UI.WebControls.TextBox username;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.TextBox address;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.HtmlControls.HtmlInputText dateofbirth;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divmsg;
		
		protected System.Web.UI.WebControls.Button register;
		
		protected System.Web.UI.WebControls.Content place2;
		
		protected System.Web.UI.WebControls.Content place3;
	}
}
