//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeFrontEnd {
	
	
	public partial class MyVeiwMaster {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder body;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder foot;
	}
}
