//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeFrontEnd {
	
	
	public partial class Passion {
		
		protected System.Web.UI.WebControls.Content place1;
		
		protected System.Web.UI.WebControls.Content place2;
		
		protected System.Web.UI.WebControls.Content place3;
	}
}
